export const SERVICE_REQUEST = "SERVICE_REQUEST";
export const SERVICE_SUCCESS = "SERVICE_SUCCESS";
export const SERVICE_FAILURE = "SERVICE_FAILURE";

export const ADD_SERVICE_REQUEST = "ADD_SERVICE_REQUEST";
export const ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS";
export const ADD_SERVICE_FAILURE = "ADD_SERVICE_FAILURE";

export const DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_FAILURE = "DELETE_SERVICE_FAILURE";

export const POST_MOBILE_REQUEST = "POST_MOBILE_REQUEST";
export const POST_MOBILE_SUCCESS = "POST_MOBILE_SUCCESS";
export const POST_MOBILE_FAILURE = "POST_MOBILE_FAILURE";

export const GET_SINGLE_SERVICE_REQUEST = "GET_SINGLE_SERVICE_REQUEST";
export const GET_SINGLE_SERVICE_SUCCESS = "GET_SINGLE_SERVICE_SUCCESS";
export const GET_SINGLE_SERVICE_FAILURE = "GET_SINGLE_SERVICE_FAILURE";

export const UPDATE_SERVICE_REQUEST = "UPDATE_SERVICE_REQUEST";
export const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS";
export const UPDATE_SERVICE_FAILURE = "UPDATE_SERVICE_FAILURE";

export const PRODUCT_TOP_REQUEST = "PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";
export const PRODUCT_TOP_FAILURE = "PRODUCT_TOP_FAILURE";

export const GET_PAGINATED_SERVICE_REQUEST = "GET_PAGINATED_SERVICE_REQUEST";
export const GET_PAGINATED_SERVICE_SUCCESS = "GET_PAGINATED_SERVICE_SUCCESS";
export const GET_PAGINATED_SERVICE_FAILURE = "GET_PAGINATED_SERVICE_FAILURE";

export const GET_SERVICES_COUNT_REQUEST = "GET_SERVICES_COUNT_REQUEST";
export const GET_SERVICES_COUNT_SUCCESS = "GET_SERVICES_COUNT_SUCCESS";
export const GET_SERVICES_COUNT_FAILURE = "GET_SERVICES_COUNT_FAILURE";
