export const SERVICE_REQUEST = 'SERVICE_REQUEST'
export const SERVICE_SUCCESS = 'SERVICE_SUCCESS'
export const SERVICE_FAILURE = 'SERVICE_FAILURE'

export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST'
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS'
export const ADD_SERVICE_FAILURE = 'ADD_SERVICE_FAILURE'

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST'
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS'
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE'

export const POST_MOBILE_REQUEST = 'POST_MOBILE_REQUEST'
export const POST_MOBILE_SUCCESS = 'POST_MOBILE_SUCCESS'
export const POST_MOBILE_FAILURE = 'POST_MOBILE_FAILURE'